set num_clients        5
set num_servers        5
set ingress_bw         10Mb
set ingress_latency    10ms
set egress_bw          10Mb
set egress_latency     10ms
set bottleneck_bw      50Mb
set bottleneck_latency 50ms
set bottleneck_qdisc   DropTail
