set num_clients        2
set num_servers        2
set ingress_bw         10Mb
set ingress_latency    1ms
set egress_bw          10Mb
set egress_latency     1ms
set bottleneck_bw      10Mb
set bottleneck_latency 1ms
set bottleneck_qdisc   DRR
