# Generated by sgb2hier-ns,sgb2hier-ns generated from sgb2ns
# sgb2ns adapted from sgb2alt by Polly Huang
# GRAPH (#nodes #edges id uu vv ww xx yy zz):
# 100 374 transtub(0,3,0,0,{1,89,3,1.000,0.000,0.000},{4,44,3,0.600,0.000,0.000},{8,36,3,0.420,0.000,0.000}) 89 2 5 0 

#Creating hierarchical topology from transit-stub graph:

proc create-hier-topology {linkBW} {
	# upvar $node n
# 	upvar $nsns ns
    global n
    global ns

	set verbose 1

	if {$verbose} { 
		puts "Creating hierarchical nodes.." 
}
set n(0) [$ns node 0.0.0]
set n(1) [$ns node 0.1.0]
set n(2) [$ns node 0.2.0]
set n(3) [$ns node 0.3.0]
set n(4) [$ns node 0.4.0]
set n(5) [$ns node 0.4.1]
set n(6) [$ns node 0.4.2]
set n(7) [$ns node 0.4.3]
set n(8) [$ns node 0.5.0]
set n(9) [$ns node 0.5.1]
set n(10) [$ns node 0.5.2]
set n(11) [$ns node 0.5.3]
set n(12) [$ns node 0.5.4]
set n(13) [$ns node 0.5.5]
set n(14) [$ns node 0.5.6]
set n(15) [$ns node 0.5.7]
set n(16) [$ns node 0.6.0]
set n(17) [$ns node 0.6.1]
set n(18) [$ns node 0.6.2]
set n(19) [$ns node 0.6.3]
set n(20) [$ns node 0.6.4]
set n(21) [$ns node 0.6.5]
set n(22) [$ns node 0.6.6]
set n(23) [$ns node 0.6.7]
set n(24) [$ns node 0.6.8]
set n(25) [$ns node 0.6.9]
set n(26) [$ns node 0.6.10]
set n(27) [$ns node 0.7.0]
set n(28) [$ns node 0.7.1]
set n(29) [$ns node 0.7.2]
set n(30) [$ns node 0.7.3]
set n(31) [$ns node 0.7.4]
set n(32) [$ns node 0.7.5]
set n(33) [$ns node 0.7.6]
set n(34) [$ns node 0.7.7]
set n(35) [$ns node 0.7.8]
set n(36) [$ns node 0.8.0]
set n(37) [$ns node 0.8.1]
set n(38) [$ns node 0.8.2]
set n(39) [$ns node 0.8.3]
set n(40) [$ns node 0.8.4]
set n(41) [$ns node 0.8.5]
set n(42) [$ns node 0.9.0]
set n(43) [$ns node 0.9.1]
set n(44) [$ns node 0.9.2]
set n(45) [$ns node 0.9.3]
set n(46) [$ns node 0.9.4]
set n(47) [$ns node 0.9.5]
set n(48) [$ns node 0.9.6]
set n(49) [$ns node 0.10.0]
set n(50) [$ns node 0.10.1]
set n(51) [$ns node 0.10.2]
set n(52) [$ns node 0.10.3]
set n(53) [$ns node 0.10.4]
set n(54) [$ns node 0.10.5]
set n(55) [$ns node 0.10.6]
set n(56) [$ns node 0.10.7]
set n(57) [$ns node 0.10.8]
set n(58) [$ns node 0.10.9]
set n(59) [$ns node 0.11.0]
set n(60) [$ns node 0.11.1]
set n(61) [$ns node 0.11.2]
set n(62) [$ns node 0.11.3]
set n(63) [$ns node 0.11.4]
set n(64) [$ns node 0.11.5]
set n(65) [$ns node 0.11.6]
set n(66) [$ns node 0.11.7]
set n(67) [$ns node 0.11.8]
set n(68) [$ns node 0.12.0]
set n(69) [$ns node 0.12.1]
set n(70) [$ns node 0.12.2]
set n(71) [$ns node 0.12.3]
set n(72) [$ns node 0.12.4]
set n(73) [$ns node 0.12.5]
set n(74) [$ns node 0.12.6]
set n(75) [$ns node 0.12.7]
set n(76) [$ns node 0.12.8]
set n(77) [$ns node 0.13.0]
set n(78) [$ns node 0.13.1]
set n(79) [$ns node 0.13.2]
set n(80) [$ns node 0.13.3]
set n(81) [$ns node 0.13.4]
set n(82) [$ns node 0.13.5]
set n(83) [$ns node 0.13.6]
set n(84) [$ns node 0.13.7]
set n(85) [$ns node 0.13.8]
set n(86) [$ns node 0.13.9]
set n(87) [$ns node 0.14.0]
set n(88) [$ns node 0.14.1]
set n(89) [$ns node 0.14.2]
set n(90) [$ns node 0.14.3]
set n(91) [$ns node 0.14.4]
set n(92) [$ns node 0.15.0]
set n(93) [$ns node 0.15.1]
set n(94) [$ns node 0.15.2]
set n(95) [$ns node 0.15.3]
set n(96) [$ns node 0.15.4]
set n(97) [$ns node 0.15.5]
set n(98) [$ns node 0.15.6]
set n(99) [$ns node 0.15.7]


# Topology information :
lappend eilevel 1 16
AddrParams set eilevel_ $eilevel
lappend eilastlevel 1 1 1 1 4 8 11 9 6 7 10 9 9 10 5 8 
AddrParams set eilastlevel_ $eilastlevel


	# EDGES (from-node to-node length a b):
	if {$verbose} { 
		puts -nonewline "Creating links 0..."
		flush stdout 
	}
	$ns duplex-link-of-interfaces $n(0) $n(29) $linkBW 320ms DropTail
	$ns duplex-link-of-interfaces $n(0) $n(17) $linkBW 240ms DropTail
	$ns duplex-link-of-interfaces $n(0) $n(12) $linkBW 170ms DropTail
	$ns duplex-link-of-interfaces $n(0) $n(4) $linkBW 310ms DropTail
	$ns duplex-link-of-interfaces $n(0) $n(2) $linkBW 450ms DropTail
	$ns duplex-link-of-interfaces $n(0) $n(3) $linkBW 250ms DropTail
	$ns duplex-link-of-interfaces $n(1) $n(63) $linkBW 30ms DropTail
	$ns duplex-link-of-interfaces $n(1) $n(53) $linkBW 280ms DropTail
	$ns duplex-link-of-interfaces $n(1) $n(44) $linkBW 10ms DropTail
	$ns duplex-link-of-interfaces $n(1) $n(40) $linkBW 300ms DropTail
	if {$verbose} { puts -nonewline "10..."; flush stdout }
	$ns duplex-link-of-interfaces $n(1) $n(2) $linkBW 120ms DropTail
	$ns duplex-link-of-interfaces $n(1) $n(3) $linkBW 190ms DropTail
	$ns duplex-link-of-interfaces $n(2) $n(88) $linkBW 230ms DropTail
	$ns duplex-link-of-interfaces $n(2) $n(80) $linkBW 160ms DropTail
	$ns duplex-link-of-interfaces $n(2) $n(69) $linkBW 80ms DropTail
	$ns duplex-link-of-interfaces $n(2) $n(3) $linkBW 210ms DropTail
	$ns duplex-link-of-interfaces $n(3) $n(95) $linkBW 190ms DropTail
	$ns duplex-link-of-interfaces $n(4) $n(5) $linkBW 90ms DropTail
	$ns duplex-link-of-interfaces $n(4) $n(7) $linkBW 230ms DropTail
	$ns duplex-link-of-interfaces $n(5) $n(6) $linkBW 160ms DropTail
	if {$verbose} { puts -nonewline "20..."; flush stdout }
	$ns duplex-link-of-interfaces $n(6) $n(7) $linkBW 180ms DropTail
	$ns duplex-link-of-interfaces $n(8) $n(9) $linkBW 170ms DropTail
	$ns duplex-link-of-interfaces $n(8) $n(11) $linkBW 100ms DropTail
	$ns duplex-link-of-interfaces $n(9) $n(10) $linkBW 210ms DropTail
	$ns duplex-link-of-interfaces $n(9) $n(12) $linkBW 60ms DropTail
	$ns duplex-link-of-interfaces $n(10) $n(12) $linkBW 250ms DropTail
	$ns duplex-link-of-interfaces $n(10) $n(15) $linkBW 320ms DropTail
	$ns duplex-link-of-interfaces $n(11) $n(12) $linkBW 170ms DropTail
	$ns duplex-link-of-interfaces $n(11) $n(13) $linkBW 170ms DropTail
	$ns duplex-link-of-interfaces $n(11) $n(15) $linkBW 230ms DropTail
	if {$verbose} { puts -nonewline "30..."; flush stdout }
	$ns duplex-link-of-interfaces $n(12) $n(13) $linkBW 10ms DropTail
	$ns duplex-link-of-interfaces $n(12) $n(14) $linkBW 150ms DropTail
	$ns duplex-link-of-interfaces $n(12) $n(15) $linkBW 60ms DropTail
	$ns duplex-link-of-interfaces $n(13) $n(14) $linkBW 140ms DropTail
	$ns duplex-link-of-interfaces $n(16) $n(18) $linkBW 130ms DropTail
	$ns duplex-link-of-interfaces $n(16) $n(20) $linkBW 160ms DropTail
	$ns duplex-link-of-interfaces $n(16) $n(25) $linkBW 180ms DropTail
	$ns duplex-link-of-interfaces $n(17) $n(20) $linkBW 160ms DropTail
	$ns duplex-link-of-interfaces $n(17) $n(23) $linkBW 190ms DropTail
	$ns duplex-link-of-interfaces $n(17) $n(24) $linkBW 80ms DropTail
	if {$verbose} { puts -nonewline "40..."; flush stdout }
	$ns duplex-link-of-interfaces $n(17) $n(25) $linkBW 160ms DropTail
	$ns duplex-link-of-interfaces $n(17) $n(26) $linkBW 170ms DropTail
	$ns duplex-link-of-interfaces $n(18) $n(19) $linkBW 160ms DropTail
	$ns duplex-link-of-interfaces $n(18) $n(21) $linkBW 170ms DropTail
	$ns duplex-link-of-interfaces $n(18) $n(22) $linkBW 320ms DropTail
	$ns duplex-link-of-interfaces $n(18) $n(24) $linkBW 220ms DropTail
	$ns duplex-link-of-interfaces $n(18) $n(26) $linkBW 340ms DropTail
	$ns duplex-link-of-interfaces $n(19) $n(20) $linkBW 170ms DropTail
	$ns duplex-link-of-interfaces $n(19) $n(21) $linkBW 130ms DropTail
	$ns duplex-link-of-interfaces $n(19) $n(22) $linkBW 190ms DropTail
	if {$verbose} { puts -nonewline "50..."; flush stdout }
	$ns duplex-link-of-interfaces $n(19) $n(23) $linkBW 200ms DropTail
	$ns duplex-link-of-interfaces $n(19) $n(24) $linkBW 90ms DropTail
	$ns duplex-link-of-interfaces $n(19) $n(25) $linkBW 170ms DropTail
	$ns duplex-link-of-interfaces $n(20) $n(21) $linkBW 110ms DropTail
	$ns duplex-link-of-interfaces $n(20) $n(22) $linkBW 60ms DropTail
	$ns duplex-link-of-interfaces $n(20) $n(23) $linkBW 190ms DropTail
	$ns duplex-link-of-interfaces $n(20) $n(25) $linkBW 30ms DropTail
	$ns duplex-link-of-interfaces $n(20) $n(26) $linkBW 210ms DropTail
	$ns duplex-link-of-interfaces $n(22) $n(24) $linkBW 100ms DropTail
	$ns duplex-link-of-interfaces $n(23) $n(24) $linkBW 190ms DropTail
	if {$verbose} { puts -nonewline "60..."; flush stdout }
	$ns duplex-link-of-interfaces $n(23) $n(26) $linkBW 340ms DropTail
	$ns duplex-link-of-interfaces $n(24) $n(26) $linkBW 150ms DropTail
	$ns duplex-link-of-interfaces $n(27) $n(30) $linkBW 220ms DropTail
	$ns duplex-link-of-interfaces $n(27) $n(32) $linkBW 170ms DropTail
	$ns duplex-link-of-interfaces $n(27) $n(34) $linkBW 110ms DropTail
	$ns duplex-link-of-interfaces $n(27) $n(35) $linkBW 80ms DropTail
	$ns duplex-link-of-interfaces $n(28) $n(31) $linkBW 230ms DropTail
	$ns duplex-link-of-interfaces $n(28) $n(33) $linkBW 200ms DropTail
	$ns duplex-link-of-interfaces $n(29) $n(30) $linkBW 330ms DropTail
	$ns duplex-link-of-interfaces $n(29) $n(33) $linkBW 100ms DropTail
	if {$verbose} { puts -nonewline "70..."; flush stdout }
	$ns duplex-link-of-interfaces $n(29) $n(34) $linkBW 190ms DropTail
	$ns duplex-link-of-interfaces $n(30) $n(34) $linkBW 320ms DropTail
	$ns duplex-link-of-interfaces $n(30) $n(35) $linkBW 300ms DropTail
	$ns duplex-link-of-interfaces $n(31) $n(33) $linkBW 30ms DropTail
	$ns duplex-link-of-interfaces $n(32) $n(33) $linkBW 90ms DropTail
	$ns duplex-link-of-interfaces $n(32) $n(35) $linkBW 250ms DropTail
	$ns duplex-link-of-interfaces $n(33) $n(35) $linkBW 230ms DropTail
	$ns duplex-link-of-interfaces $n(36) $n(38) $linkBW 250ms DropTail
	$ns duplex-link-of-interfaces $n(36) $n(41) $linkBW 80ms DropTail
	$ns duplex-link-of-interfaces $n(37) $n(40) $linkBW 10ms DropTail
	if {$verbose} { puts -nonewline "80..."; flush stdout }
	$ns duplex-link-of-interfaces $n(37) $n(41) $linkBW 280ms DropTail
	$ns duplex-link-of-interfaces $n(38) $n(39) $linkBW 150ms DropTail
	$ns duplex-link-of-interfaces $n(38) $n(40) $linkBW 10ms DropTail
	$ns duplex-link-of-interfaces $n(42) $n(43) $linkBW 190ms DropTail
	$ns duplex-link-of-interfaces $n(42) $n(44) $linkBW 100ms DropTail
	$ns duplex-link-of-interfaces $n(42) $n(45) $linkBW 80ms DropTail
	$ns duplex-link-of-interfaces $n(43) $n(44) $linkBW 140ms DropTail
	$ns duplex-link-of-interfaces $n(43) $n(47) $linkBW 110ms DropTail
	$ns duplex-link-of-interfaces $n(43) $n(48) $linkBW 150ms DropTail
	$ns duplex-link-of-interfaces $n(44) $n(45) $linkBW 110ms DropTail
	if {$verbose} { puts -nonewline "90..."; flush stdout }
	$ns duplex-link-of-interfaces $n(45) $n(46) $linkBW 310ms DropTail
	$ns duplex-link-of-interfaces $n(45) $n(47) $linkBW 110ms DropTail
	$ns duplex-link-of-interfaces $n(46) $n(48) $linkBW 180ms DropTail
	$ns duplex-link-of-interfaces $n(47) $n(48) $linkBW 50ms DropTail
	$ns duplex-link-of-interfaces $n(49) $n(53) $linkBW 350ms DropTail
	$ns duplex-link-of-interfaces $n(49) $n(58) $linkBW 350ms DropTail
	$ns duplex-link-of-interfaces $n(50) $n(52) $linkBW 210ms DropTail
	$ns duplex-link-of-interfaces $n(50) $n(56) $linkBW 250ms DropTail
	$ns duplex-link-of-interfaces $n(51) $n(53) $linkBW 220ms DropTail
	$ns duplex-link-of-interfaces $n(51) $n(56) $linkBW 230ms DropTail
	if {$verbose} { puts -nonewline "100..."; flush stdout }
	$ns duplex-link-of-interfaces $n(51) $n(57) $linkBW 280ms DropTail
	$ns duplex-link-of-interfaces $n(51) $n(58) $linkBW 170ms DropTail
	$ns duplex-link-of-interfaces $n(52) $n(54) $linkBW 10ms DropTail
	$ns duplex-link-of-interfaces $n(52) $n(56) $linkBW 180ms DropTail
	$ns duplex-link-of-interfaces $n(52) $n(58) $linkBW 110ms DropTail
	$ns duplex-link-of-interfaces $n(53) $n(54) $linkBW 80ms DropTail
	$ns duplex-link-of-interfaces $n(53) $n(55) $linkBW 260ms DropTail
	$ns duplex-link-of-interfaces $n(53) $n(58) $linkBW 70ms DropTail
	$ns duplex-link-of-interfaces $n(54) $n(55) $linkBW 180ms DropTail
	$ns duplex-link-of-interfaces $n(54) $n(58) $linkBW 120ms DropTail
	if {$verbose} { puts -nonewline "110..."; flush stdout }
	$ns duplex-link-of-interfaces $n(55) $n(58) $linkBW 300ms DropTail
	$ns duplex-link-of-interfaces $n(56) $n(57) $linkBW 50ms DropTail
	$ns duplex-link-of-interfaces $n(56) $n(58) $linkBW 250ms DropTail
	$ns duplex-link-of-interfaces $n(59) $n(60) $linkBW 180ms DropTail
	$ns duplex-link-of-interfaces $n(59) $n(61) $linkBW 80ms DropTail
	$ns duplex-link-of-interfaces $n(59) $n(63) $linkBW 30ms DropTail
	$ns duplex-link-of-interfaces $n(60) $n(63) $linkBW 190ms DropTail
	$ns duplex-link-of-interfaces $n(60) $n(66) $linkBW 140ms DropTail
	$ns duplex-link-of-interfaces $n(60) $n(67) $linkBW 130ms DropTail
	$ns duplex-link-of-interfaces $n(61) $n(63) $linkBW 70ms DropTail
	if {$verbose} { puts -nonewline "120..."; flush stdout }
	$ns duplex-link-of-interfaces $n(61) $n(64) $linkBW 30ms DropTail
	$ns duplex-link-of-interfaces $n(61) $n(67) $linkBW 140ms DropTail
	$ns duplex-link-of-interfaces $n(62) $n(64) $linkBW 100ms DropTail
	$ns duplex-link-of-interfaces $n(62) $n(67) $linkBW 180ms DropTail
	$ns duplex-link-of-interfaces $n(63) $n(65) $linkBW 120ms DropTail
	$ns duplex-link-of-interfaces $n(63) $n(66) $linkBW 220ms DropTail
	$ns duplex-link-of-interfaces $n(63) $n(67) $linkBW 80ms DropTail
	$ns duplex-link-of-interfaces $n(65) $n(67) $linkBW 60ms DropTail
	$ns duplex-link-of-interfaces $n(66) $n(67) $linkBW 210ms DropTail
	$ns duplex-link-of-interfaces $n(68) $n(72) $linkBW 320ms DropTail
	if {$verbose} { puts -nonewline "130..."; flush stdout }
	$ns duplex-link-of-interfaces $n(68) $n(74) $linkBW 70ms DropTail
	$ns duplex-link-of-interfaces $n(69) $n(70) $linkBW 100ms DropTail
	$ns duplex-link-of-interfaces $n(69) $n(71) $linkBW 70ms DropTail
	$ns duplex-link-of-interfaces $n(69) $n(75) $linkBW 220ms DropTail
	$ns duplex-link-of-interfaces $n(70) $n(71) $linkBW 50ms DropTail
	$ns duplex-link-of-interfaces $n(70) $n(73) $linkBW 240ms DropTail
	$ns duplex-link-of-interfaces $n(70) $n(76) $linkBW 220ms DropTail
	$ns duplex-link-of-interfaces $n(71) $n(73) $linkBW 190ms DropTail
	$ns duplex-link-of-interfaces $n(71) $n(75) $linkBW 220ms DropTail
	$ns duplex-link-of-interfaces $n(71) $n(76) $linkBW 180ms DropTail
	if {$verbose} { puts -nonewline "140..."; flush stdout }
	$ns duplex-link-of-interfaces $n(73) $n(74) $linkBW 240ms DropTail
	$ns duplex-link-of-interfaces $n(73) $n(75) $linkBW 40ms DropTail
	$ns duplex-link-of-interfaces $n(74) $n(76) $linkBW 260ms DropTail
	$ns duplex-link-of-interfaces $n(75) $n(76) $linkBW 190ms DropTail
	$ns duplex-link-of-interfaces $n(77) $n(79) $linkBW 100ms DropTail
	$ns duplex-link-of-interfaces $n(77) $n(82) $linkBW 210ms DropTail
	$ns duplex-link-of-interfaces $n(78) $n(79) $linkBW 250ms DropTail
	$ns duplex-link-of-interfaces $n(78) $n(81) $linkBW 150ms DropTail
	$ns duplex-link-of-interfaces $n(78) $n(83) $linkBW 240ms DropTail
	$ns duplex-link-of-interfaces $n(78) $n(85) $linkBW 220ms DropTail
	if {$verbose} { puts -nonewline "150..."; flush stdout }
	$ns duplex-link-of-interfaces $n(78) $n(86) $linkBW 70ms DropTail
	$ns duplex-link-of-interfaces $n(79) $n(83) $linkBW 100ms DropTail
	$ns duplex-link-of-interfaces $n(79) $n(86) $linkBW 220ms DropTail
	$ns duplex-link-of-interfaces $n(80) $n(84) $linkBW 310ms DropTail
	$ns duplex-link-of-interfaces $n(80) $n(85) $linkBW 340ms DropTail
	$ns duplex-link-of-interfaces $n(81) $n(82) $linkBW 130ms DropTail
	$ns duplex-link-of-interfaces $n(81) $n(84) $linkBW 230ms DropTail
	$ns duplex-link-of-interfaces $n(82) $n(83) $linkBW 260ms DropTail
	$ns duplex-link-of-interfaces $n(82) $n(84) $linkBW 300ms DropTail
	$ns duplex-link-of-interfaces $n(82) $n(85) $linkBW 270ms DropTail
	if {$verbose} { puts -nonewline "160..."; flush stdout }
	$ns duplex-link-of-interfaces $n(82) $n(86) $linkBW 230ms DropTail
	$ns duplex-link-of-interfaces $n(83) $n(85) $linkBW 40ms DropTail
	$ns duplex-link-of-interfaces $n(83) $n(86) $linkBW 190ms DropTail
	$ns duplex-link-of-interfaces $n(84) $n(85) $linkBW 250ms DropTail
	$ns duplex-link-of-interfaces $n(84) $n(86) $linkBW 100ms DropTail
	$ns duplex-link-of-interfaces $n(85) $n(86) $linkBW 160ms DropTail
	$ns duplex-link-of-interfaces $n(87) $n(88) $linkBW 60ms DropTail
	$ns duplex-link-of-interfaces $n(87) $n(89) $linkBW 180ms DropTail
	$ns duplex-link-of-interfaces $n(87) $n(90) $linkBW 70ms DropTail
	$ns duplex-link-of-interfaces $n(87) $n(91) $linkBW 210ms DropTail
	if {$verbose} { puts -nonewline "170..."; flush stdout }
	$ns duplex-link-of-interfaces $n(88) $n(90) $linkBW 10ms DropTail
	$ns duplex-link-of-interfaces $n(89) $n(90) $linkBW 120ms DropTail
	$ns duplex-link-of-interfaces $n(89) $n(91) $linkBW 160ms DropTail
	$ns duplex-link-of-interfaces $n(90) $n(91) $linkBW 200ms DropTail
	$ns duplex-link-of-interfaces $n(92) $n(93) $linkBW 130ms DropTail
	$ns duplex-link-of-interfaces $n(92) $n(99) $linkBW 120ms DropTail
	$ns duplex-link-of-interfaces $n(93) $n(95) $linkBW 210ms DropTail
	$ns duplex-link-of-interfaces $n(93) $n(98) $linkBW 220ms DropTail
	$ns duplex-link-of-interfaces $n(93) $n(99) $linkBW 230ms DropTail
	$ns duplex-link-of-interfaces $n(94) $n(95) $linkBW 50ms DropTail
	if {$verbose} { puts -nonewline "180..."; flush stdout }
	$ns duplex-link-of-interfaces $n(94) $n(96) $linkBW 90ms DropTail
	$ns duplex-link-of-interfaces $n(94) $n(97) $linkBW 360ms DropTail
	$ns duplex-link-of-interfaces $n(94) $n(99) $linkBW 130ms DropTail
	$ns duplex-link-of-interfaces $n(95) $n(97) $linkBW 390ms DropTail
	$ns duplex-link-of-interfaces $n(95) $n(98) $linkBW 310ms DropTail
	$ns duplex-link-of-interfaces $n(96) $n(97) $linkBW 390ms DropTail
	$ns duplex-link-of-interfaces $n(98) $n(99) $linkBW 170ms DropTail

	if {$verbose} { 
		puts -nonewline "187..."
		flush stdout
		puts "starting"
	}
	return 100}
# end of hier topology generation
