#! /bin/sh

#
# Copyright (c) 1997 University of Southern California.
# All rights reserved.                                            
#                                                                
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation, advertising
# materials, and other materials related to such distribution and use
# acknowledge that the software was developed by the University of
# Southern California, Information Sciences Institute.  The name of the
# University may not be used to endorse or promote products derived from
# this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
# 

#
# @(#) $Header: /cvsroot/nsnam/ns-2/tcl/test/test-all-rbp,v 1.2 2000/10/03 03:12:03 sfloyd Exp $
#

file="test-suite-rbp.tcl"
directory="test-output-rbp"
version="v2"
if [ $# -ge 1 ]
then
	flag=$*
	./test-all-template1 $file $directory $version $flag
else
	./test-all-template1 $file $directory $version
fi
