#! /bin/sh

#
# Copyright (c) 1998 University of Southern California.
# All rights reserved.                                            
#                                                                
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation, advertising
# materials, and other materials related to such distribution and use
# acknowledge that the software was developed by the University of
# Southern California, Information Sciences Institute.  The name of the
# University may not be used to endorse or promote products derived from
# this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
# 
# Contributed by Rishi Bhargava <rishi_bhargava@yahoo.com> May, 2001.
#
# @(#) $Header: /cvsroot/nsnam/ns-2/tcl/test/test-all-source-routing,v 1.1 2001/05/29 20:53:31 haldar Exp $
#

feature="source-routing"
file="test-suite-$feature.tcl"
directory="test-output-$feature"
version="v2"
./test-all-template1 $file $directory $version $@
